version: '3.8'

services:
  web:
    container_name: Contact_Form
    image: projet_contact_form
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    env_file:
      - ${PWD}/build/docker-compose.env
      - ${PWD}/build/SMTP.env
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/styles:/app/styles
      - ${PWD}/scss:/app/scss
      - ${PWD}/dist:/app/dist
    depends_on:
      - postgres_db
    working_dir: /app
    command: [ "npm", "run", "dev" ]

  postgres_db:
    container_name: postgres_db_message
    image: postgres
    restart: always
    env_file:
      - ${PWD}/build/docker-compose.env
    volumes:
      - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  adminer:
    container_name: adminer_contact_form
    image: adminer
    restart: always
    ports:
      - "8180:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres_db"
    depends_on:
      - postgres_db
