version: '3.8'

services:
  web:
    container_name: Form_Contact
    image: projetformcontact
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "start.js"]

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=contact-form
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

    volumes:
      - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - "5433:5432"
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8180:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres_db"

