version: '3.8'

services:
  web:
    container_name: Contact_Form
    image: projet_contact_form
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    env_file:
      - ${PWD}/build/environnements.env
      - ${PWD}/build/postgres.env
      - ${PWD}/build/SMTP.env
      - ${PWD}/build/maildev.env
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/styles:/app/styles
      - ${PWD}/scss:/app/scss
      - ${PWD}/dist:/app/dist
    depends_on:
      - postgres_db
    working_dir: /app
    command: npm run dev

  postgres_db:
    container_name: postgres_db_message
    image: postgres
    restart: always
    env_file:
      - ${PWD}/build/postgres.env
    volumes:
      - ${PWD}/DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${PWD}/DataBase/postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    container_name: adminer_contact_form
    image: adminer
    restart: always
    ports:
      - "8180:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres_db"
    depends_on:
      - postgres_db

  maildev:
    container_name: devmail_contact_form
    image: maildev/maildev
    restart: always
    env_file:
      - ${PWD}/build/maildev.env
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  postgres-data:


